[package]
name = "sanctum-svc-jiminy"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
sanctum-svc-core = { workspace = true }
jiminy-cpi = { workspace = true }
jiminy-return-data = { workspace = true }
