[package]
name = "inf1-svc-jiminy"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
inf1-svc-core = { workspace = true }
jiminy-cpi = { workspace = true }
jiminy-return-data = { workspace = true }
