[package]
name = "sanctum-svc-wsol-std"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
sanctum-svc-wsol-core = { workspace = true }
sanctum-svc-std = { workspace = true }
