[package]
name = "sanctum-svc-wsol-core"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
const-crypto = { workspace = true }
sanctum-svc-core = { workspace = true }
generic-array-struct = { workspace = true }
