[package]
name = "inf1-svc-wsol-core"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
const-crypto = { workspace = true }
inf1-svc-core = { workspace = true }
generic-array-struct = { workspace = true }
