[package]
name = "sanctum-svc-std"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
sanctum-svc-core = { workspace = true }
sanctum-update-traits = { workspace = true }
